// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID             string         `json:"id"`
	FirstName      string         `json:"first_name"`
	Email          string         `json:"email"`
	Phone          string         `json:"phone"`
	BirthDate      int64          `json:"birth_date"`
	Gender         string         `json:"gender"`
	ShowMe         string         `json:"show_me"`
	University     sql.NullString `json:"university"`
	Nsfw           bool           `json:"nsfw"`
	Ethnicity      string         `json:"ethnicity"`
	Interests      []string       `json:"interests"`
	Picture        []string       `json:"picture"`
	VerifyYourself sql.NullBool   `json:"verify_yourself"`
	AboutMe        sql.NullString `json:"about_me"`
	TimeZone       sql.NullString `json:"time_zone"`
	CreatedAt      time.Time      `json:"created_at"`
}

type Favourite struct {
	FavID    uuid.UUID `json:"fav_id"`
	UserID   string    `json:"user_id"`
	TargetID string    `json:"target_id"`
	FavAt    time.Time `json:"fav_at"`
}
